### ISSUE TITLE
Require symfony/scheduler

### ISSUE THREAD

**Issue by balazscsaba2006** [zenstruck/messenger-monitor-bundle#12]
The bundle seems to have a hard dependency on the new `symfony/scheduler`, even if we use a proprietary scheduler, to load the scheduler service. IMO it should be required in composer.json as:
```json
"symfony/scheduler": "^6.3",
```

**Comment by kbond** [comment]
Can you elaborate? It is in require-dev.

**Comment by balazscsaba2006** [comment]
Just by running `composer require zenstruck/messenger-monitor-bundle` the scheduler is not installed, and because of this check https://github.com/zenstruck/messenger-monitor-bundle/blob/1.x/src/DependencyInjection/ZenstruckMessengerMonitorExtension.php#L78 the scheduler related services are not loaded at all.  Maybe there's a better solution to this problem.

**Comment by kbond** [comment]
Ok, that's intended but is there an error? I might have missed something. I want the dashboard to work without scheduler if not available.

**Comment by balazscsaba2006** [comment]
Yes, as we've tried injecting the `Storage` service into our custom service, and 
```bash
The service ".zenstruck_messenger_monitor.command.schedule_purge" has a dependency on a non-existent service "zenstruck_messenger_monitor.schedules". Did you mean one of these: "zenstruck_m  
  essenger_monitor.transports", "zenstruck_messenger_monitor.workers", "zenstruck_messenger_monitor.view_helper"?
```

**Comment by kbond** [comment]
Oh ok, yeah definitely a bug then.
