### ISSUE TITLE
0.5 - Unrecognized option "live_components" under "zenstruck_messenger_monitor".  

### ISSUE THREAD

**Issue by Chris53897** [zenstruck/messenger-monitor-bundle#121]
Upgrading from 0.4 to 0.5 i get this error.

`0.5 - Unrecognized option "live_components" under "zenstruck_messenger_monitor".
Available options are "cache", "storage".`

I guess this is not expected.
https://github.com/zenstruck/messenger-monitor-bundle/blob/1.x/UPGRADE.md#050

**Comment by bobvandevijver** [comment]
The live components have been removed, the upgrade documentation has been updated.

**Comment by Chris53897** [comment]
Thanks @bobvandevijver
