### ISSUE TITLE
Store message context

### ISSUE THREAD

**Issue by bobvandevijver** [zenstruck/messenger-monitor-bundle#122]
Currently, only the message result (the return value of the message handler) is recorded in the data field of the results. However, I would like to be able to store some context of the message (such as the entity id that the message was scheduled for) that is handled so I can use that for debugging. For example, this weekend I was using the processed messages to basically create a trail for an issue a user noted to debunk their story, for which having that information in the log would have been useful.

As I keep the message content usually quite small, a full serialized version of the original value would already work.

**Comment by kbond** [comment]
#46?

**Comment by bobvandevijver** [comment]
Ah yes, this is indeed a duplicate of #46 / #17!
