### ISSUE TITLE
new setup,empty queue snapshot.totalcount throws exception 

### ISSUE THREAD

**Issue by golliholzland** [zenstruck/messenger-monitor-bundle#16]
![image](https://github.com/zenstruck/messenger-monitor-bundle/assets/132348430/2f6aa9ba-a930-4571-8927-3a2672997658)
Query needs to be checked.

**Comment by golliholzland** [comment]
with more investigation, I found out that the error is caused by PostgresSQL, I guess there is no support yet

**Comment by kbond** [comment]
Thanks for reporting. Must be this method:

https://github.com/zenstruck/messenger-monitor-bundle/blob/8ad6125c5f7618231035dcacddfa6d36638b6d0a/src/History/Storage/ORMStorage.php#L97-L103

I'll look into this.

**Comment by kbond** [comment]
Looks like you can't have a count & order by w/o a group by in postgres: https://stackoverflow.com/questions/45096178/count-with-order-by-not-working-on-postgresql-which-works-on-oracle

**Comment by golliholzland** [comment]
yes it is, Actually all function will throw the same error, I solved it using groupBy(m.id)
`
$this->queryBuilderFor($specification)->select('COUNT(m.finishedAt)')->groupBy(m.id)
`,

**Comment by kbond** [comment]
Do the `AVG()`'s have the same problem?

**Comment by golliholzland** [comment]
yes is is required with all aggregate functions

**Comment by kbond** [comment]
The id property name is not enforced.

~Would it work if I use `->groupBy('m.finishedAt')`. Or.. would that be a problem if multiple rows had the same `finishedAt` value?~

I can use class metadata to get the id property name.

**Comment by kbond** [comment]
This should be fixed in a4fc554d0e9a793f404e5f18767f7f4d06258d6d. Let me know if it isn't.

Thanks again for testing this bundle for me!
