### ISSUE TITLE
0 workers found

### ISSUE THREAD

**Issue by golliholzland** [zenstruck/messenger-monitor-bundle#18]
This issue occurs on my production environment where the workers are on different containers, each worker has its own storage, I believe you read how many workers from the cache and that's why I get 0 workers on my main container. It would be nice if you explain how you check for workers in order to debug this issue

**Comment by kbond** [comment]
Hey, the worker details are stored in `app.cache`. Do your containers not share this?

**Comment by golliholzland** [comment]
sharing cache between workers would result on server error

**Comment by kbond** [comment]
Hmm, ok, I don't have any experience with containerized workers but isn't a shared cache something that should be possible? I'm a bit surprised you don't have any shared state between your workers and app.

If you can't use app.cache, could you create a shared cache that's just for this bundle? I'd have to make the cache service configurable.

**Comment by golliholzland** [comment]
yes currently, we can't configure the cache service, and i believe it is better to use another adapter then filesystem. I will update my comment once i have made these changes.

**Comment by kbond** [comment]
> i believe it is better to use another adapter then filesystem

Yeah, you'd need something like redis
