### ISSUE TITLE
Make logging optional

### ISSUE THREAD

**Issue by Chris53897** [zenstruck/messenger-monitor-bundle#20]
If i start the consuming, the console is flooded with the debug-infos.
Could that be an optional function to configure in `zenstruck_messenger_monitor.yaml`?

`symfony console messenger:consume async -vv `

` [cache] Lock acquired, now computing item "zenstruck_messenger_monitor.worker.119254" ["key" => "zenstruck_messenger_monitor.worker.119254"]`

**Comment by kbond** [comment]
I noticed that as well... I don't think there's anything we can/should do in this bundle. I think you'd need to configure your console log handler to exclude `cache` logs: https://github.com/symfony/recipes/blob/11095f4c8f6c1cdbca00c9649e2628f1c0c1d338/symfony/monolog-bundle/3.7/config/packages/monolog.yaml#L24
