### ISSUE TITLE
Update/Close Worker-Status after cancelation of messenger? (Upstream Bug)

### ISSUE THREAD

**Issue by Chris53897** [zenstruck/messenger-monitor-bundle#24]
If i run `symfony console messenger:consume async` and end it with CTRL+C
And repeat this 3 times. I got the following stats in the UI.

I am not sure what is the desired behaviour.
Status of Worker 1-3 should not be `idle`. `killed` ?
Remove killed Workers from the UI?

Are the worker killed correctly?

  | Status | Transports | # Handled | Memory
-- | -- | -- | -- | --
1 | idle | async | 5 | 73.92 MB
2 | idle | async | 10 | 88.60 MB
3 | idle | async | 2 | 65.54 MB
4 | idle | async | 0 | 44.56 MB

**Comment by Chris53897** [comment]
I used Symfony 6.3.5.
Maybe related to https://github.com/symfony/symfony/pull/52080
I will test later with 6.3.4.

**Comment by Chris53897** [comment]
I see the status is supposed to be `idle` and `processing`.
If i clear the symfony cache the data is reseted.

If i run in console a) `symfony console messenger:consume async`
and in console b) `symfony console messenger:stop-workers`
it works like desired.

The worker is stopped correctly, and removed from the cache (and in the ui).

I am not sure if this https://github.com/HypeMC/symfony/blob/b270382f1f599efa0f833ab01693a29c60551bd8/src/Symfony/Component/Messenger/Command/ConsumeMessagesCommand.php#L264
does dispatch the event WorkerStopped.

Look like this is not the case.
https://github.com/HypeMC/symfony/blob/6.3/src/Symfony/Component/Messenger/Worker.php#L269

As this does look like a bug (desired behaviour) in symfony, i will open an issue there.

**Comment by Chris53897** [comment]
https://github.com/symfony/symfony/pull/52123

**Comment by kbond** [comment]
I did notice this problem but wasn't sure what it was! Glad it was fixed upstream. Can you confirm it works correctly now?

**Comment by Chris53897** [comment]
Yes, i can confirm that symfony/messenger 6.3.6 does fix this. I will close this isssue
