### ISSUE TITLE
LiveComponents: Pause and Intervall

### ISSUE THREAD

**Issue by Chris53897** [zenstruck/messenger-monitor-bundle#28]
It would be great to make it work like RabbitMQ for the live-View.
A Pause-Button and a Dropdown (or something simiilar) to change the intervall of the Updates.
With an option to set a default in `zenstruck_messenger_monitor.yaml` like

**Comment by kbond** [comment]
You mean on the dashboard: auto-update the message list? I think we can do this with another optional live component (like the other widgets).

**Comment by Chris53897** [comment]
Yes the dashboard. I do not have much knowledge about live components. That would be a better solution than mine. I had something like the meta-refresh in mind.
https://www.quackit.com/html/codes/meta_refresh.cfm

**Comment by kbond** [comment]
> something like the meta-refresh in mind.

That would refresh the whole page, right? That could be troublesome if you're in the middle of choosing a filter.

**Comment by kbond** [comment]
Closing as I've removed the live-components.
