### ISSUE TITLE
Releases / Tags?

### ISSUE THREAD

**Issue by deeky666** [zenstruck/messenger-monitor-bundle#35]
Hey there,

are you planning to add releases or tags to pin versions of the bundle? Is it considered "stable" already?

**Comment by kbond** [comment]
> Is it considered "stable" already?

No, I have at least one breaking change I want to make before a 1.0.

> are you planning to add releases or tags to pin versions of the bundle?

Yes, I hope to find the time to push this to a 1.0 by the end of the year. For now, I'm just collecting feedback from early testers.

**Comment by deeky666** [comment]
Thank you for letting me know. Really looking forward to this baby then :) Keep up the good work!

**Comment by kkevindev** [comment]
> > Is it considered "stable" already?
> 
> No, I have at least one breaking change I want to make before a 1.0.
> 
> > are you planning to add releases or tags to pin versions of the bundle?
> 
> Yes, I hope to find the time to push this to a 1.0 by the end of the year. For now, I'm just collecting feedback from early testers.

@kbond was the breaking change you were talking about the one in the 0.6.0 release? If so: Shouldn't it have been bumped to a 1.0.0 version? If not: when is a 1.0.0 (stable) version planned?

**Comment by Chris53897** [comment]
one breaking change would be
https://github.com/zenstruck/messenger-monitor-bundle/pull/46
