### ISSUE TITLE
schedule.html.twig doesn't work without csrf enabled

### ISSUE THREAD

**Issue by Lappihuan** [zenstruck/messenger-monitor-bundle#41]
would it be possible to make csrf optional for [schedule.html.twig](file:///srv/app/vendor/zenstruck/messenger-monitor-bundle/templates/schedule.html.twig#L167)?

we don't use sessions so we can't enable csrf from what i can tell.

**Comment by kbond** [comment]
Yes, this should be doable. I'm thinking to just not use if csrf isn't enabled (rather than a config option). Would that work for you?

**Comment by Lappihuan** [comment]
Sounds good
