### ISSUE TITLE
`RecurringMessage::getMessage()` was removed in favor of `getMessages()`

### ISSUE THREAD

**Issue by Chris53897** [zenstruck/messenger-monitor-bundle#51]
Error: Call to an undefined method Symfony\Component\Scheduler\RecurringMessage::getMessage().

This class has only getMessages()
https://github.com/symfony/symfony/blob/6.4/src/Symfony/Component/Scheduler/RecurringMessage.php

I did not take a closer look yet.

**Comment by kbond** [comment]
There was a BC break here from 6.3-6.4: https://github.com/symfony/symfony/pull/51542

I'm going to have to rethink this 🤔

**Comment by kbond** [comment]
I believe this was fixed in #65
