### ISSUE TITLE
Redispatch Failed Message

### ISSUE THREAD

**Issue by alessandro-podo** [zenstruck/messenger-monitor-bundle#52]
At the moment, you can see in the overview which messages have failed.
When I'm on the go, I often don't have good access to the console to re-dispatch a message.

It would be practical if we had a button in the UI that could be used to trigger a retry.

Is this something that fits in the bundle?

**Comment by kbond** [comment]
Yes, this is planned (#15)

**Comment by alessandro-podo** [comment]
thanks, sorry i didnt see your issue
