### ISSUE TITLE
"composer require zenstruck/messenger-monitor-bundle" does not work

### ISSUE THREAD

**Issue by mehmetsen80** [zenstruck/messenger-monitor-bundle#64]
I guess since it's not tagged yet I am having the below error?

 Could not find a version of package zenstruck/messenger-monitor-bundle matching 

you want to update your document as: 

composer require  zenstruck/messenger-monitor-bundle 1.x-dev

**Comment by kbond** [comment]
I've created a [pre-release](https://github.com/zenstruck/messenger-monitor-bundle/releases/tag/v0.1.0).
