### ISSUE TITLE
Wrong calculated history of handled messages

### ISSUE THREAD

**Issue by Chris53897** [zenstruck/messenger-monitor-bundle#88]
It is just for me or is the calculated history of handled messages incorrect?
The Snapshot-Data should be `All Time` and `29099 (1 failues)`. Instead of `2 (1 failues)`
Or on what Data is the snapshot based on?

<img width="1888" alt="Wrong History" src="https://github.com/zenstruck/messenger-monitor-bundle/assets/7104259/c3a8008c-55b9-4b63-ab68-14b5828c8ed8">

**Comment by Chris53897** [comment]
I will close this Issue as duplicate of https://github.com/zenstruck/messenger-monitor-bundle/issues/83

@kbond Could you please tag a new release?

**Comment by kbond** [comment]
Released v0.3.0.
