### ISSUE TITLE
SQL bug while rendering the homepage

### ISSUE THREAD

**Issue by maidmaid** [zenstruck/messenger-monitor-bundle#96]
By upgrading the package from 1.x-dev 8315f51 to 1.x-dev 1f875b0, I got :

> An exception has been thrown during the rendering of a template ("An exception occurred while executing a query: SQLSTATE[42803]: Grouping error: 7 ERROR: column "m0_.finished_at" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: ...ed_at >= $1 AND m0_.failure_type IS NULL ORDER BY m0_.finish...
^").

The error come from `{{ snapshot.totalCount }}` in vendor/zenstruck/messenger-monitor-bundle/templates/components/snapshot.html.twig:19

I use posgresql as driver.

**Comment by Chris53897** [comment]
Please see https://github.com/zenstruck/messenger-monitor-bundle/pull/90
You can use Version 0.2.0 until this is merged.

**Comment by kbond** [comment]
I just merged and released.

**Comment by Chris53897** [comment]
@maidmaid Can your test it with 0.4.0 and confirm, that it works?
After that, this issue can be closed.
