### ISSUE TITLE
PostgreSQL averageWaitTime & averageHandlingTime are not working

### ISSUE THREAD

**Issue by SherinBloemendaal** [zenstruck/messenger-monitor-bundle#97]
We are using PostgreSQL and the averageWaitTime and averageHandlingTime always result to `0.0`.
(`$this->storage->averageWaitTime(new Specification())`)

As far as I can see the following query is executed (in case of `averageWaitTime`):
```
SELECT AVG(p0_.received_at - p0_.dispatched_at) AS sclr_0 FROM processed_message p0_ LIMIT 1;
```

Resulting into this:
```
array:1 [
  1 => "00:02:22.468872"
]
```

Inside the [ORMStorage.php#L98](https://github.com/zenstruck/messenger-monitor-bundle/blob/72568b7e2b98044f9f272f831fa32704752bdb31/src/History/Storage/ORMStorage.php#L98) its being casted to a `float` which is not working in this scenario because the string is not formatted as float.

Is this a known problem? I can create a pull request but I am curious how this should be fixed because I guess the problem doesn't exist in MySQL :)

**Comment by kbond** [comment]
Wow, I didn't realize postgres calculates timestamp differences this way. I'm also not sure how this can be fixed in a clean way...

Pretty sure others are using this bundle with postgres, anyone have any insight?

**Comment by Chris53897** [comment]
I guess most messages are handled under one second, that is why it was not discovered before. Or nobody did care before.

I did have a look with Postgres.
This is the opposite of clean, but it works for me.
Maybe Microseconds are not needed?

```
if($targedTime = \DateTime::createFromFormat('h:i:U.u', (new EntityResult($qb))->asScalar()->first()));
        else{$targedTime = \DateTime::createFromFormat('h:i:U', (new EntityResult($qb))->asScalar()->first());}

        return ($targedTime->format('H')*3600 + ($targedTime->format('i')*60 + $targedTime->format('s') + $targedTime->format('U.u')));
```

**Comment by kbond** [comment]
So I'm sort of seeing 2 options here:
1. DB-specific code for doing the timestamp diffs
2. Store the values in the db (2 extra integer fields: handling_time, wait_time)

To me, (2) seems like the easiest but what do you think?
